import { styleTags, tags as t } from "@lezer/highlight"

export const scalaHighlighting = styleTags({
  "package import export": t.moduleKeyword,
  "class trait object enum case given extension": t.definitionKeyword,
  "def val var type lazy": t.definitionKeyword,
  "opaque": t.modifier,
  "if else while do for match try catch finally return throw yield": t.controlKeyword,
  "then": t.controlKeyword,
  "abstract final sealed open private protected override implicit inline transparent": t.modifier,
  "using derives extends with": t.modifier,
  "new super this": t.self,
  "true false null": t.atom,
  "Unit Nothing Any String Int Boolean": t.typeName,
  TypeIdentifier: t.typeName,
  Identifier: t.variableName,
  Number: t.number,
  String: t.string,
  InterpolatedString: t.special(t.string),
  XmlLiteral: t.string,
  XmlTag: t.tagName,
  XmlAttribute: t.attributeName,
  LineComment: t.lineComment,
  BlockComment: t.blockComment,
  ScaladocComment: t.docComment,
  Scaladoc: t.docComment,
  Annotation: t.annotation,
  "( )": t.paren,
  "[ ]": t.squareBracket,
  "{ }": t.brace,
  ". , ; :": t.punctuation,
  "=": t.definitionOperator,
  "=> -> <- =>> ?=>": t.operator,
  "| &": t.operator,
  "+ - * / % == != < > <= >= && || ! => -> <- # :: ::: ^ ~ `": t.operator,
  "_": t.punctuation
})
